select * from customer limit 20

-- What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender  

-- Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)
        

-- Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating)::numeric,2) as high_rating
from customer
group by item_purchased
order by high_rating desc
limit 5


-- Compare the average purchase amounts between Standard and Express shipping.
select shipping_type,round(avg(purchase_amount),2) as avg_amt
from customer
where shipping_type='Standard' or shipping_type='Express'
--where shipping_type in('Standard','Express')
group by shipping_type



-- Do subscribed customers spend more-NO? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_amt,sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_amt,total_revenue


-- Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)*100/count(*),2) as percentage
from customer
group by item_purchased
order by percentage desc
limit 5



-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
CASE 
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment



-- What are the top 3 most purchased products within each category?


with cte as(
select category,item_purchased,count(*) as cnt
from customer
group by category,item_purchased
order by category,cnt desc
)

select category,item_purchased,cnt
from(
select category,item_purchased,cnt,
row_number() over(partition by category order by cnt desc) as rnk
from cte
)
where rnk<=3

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?No
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5 
group by subscription_status

-- What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc
